# Generated by Django 5.1.2 on 2024-10-14 03:44

import banjo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scavenger_hunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_posted', banjo.models.StringField(default='')),
                ('location', banjo.models.IntegerField(default=0)),
                ('hint', banjo.models.StringField(default='')),
                ('description', banjo.models.StringField(default='')),
                ('code', banjo.models.StringField(default='')),
                ('complete', banjo.models.BooleanField(default=False)),
                ('active', banjo.models.BooleanField(default=False)),
                ('user_completed', banjo.models.StringField(default='')),
                ('likes', banjo.models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
