# Generated by Django 5.1.2 on 2024-10-15 07:27

import banjo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_scavenger_hunt_current_scavenger_hunt_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', banjo.models.StringField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
