# Generated by Django 5.1.2 on 2024-10-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
