# Generated by Django 5.1.2 on 2024-10-18 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scavenger_hunt',
            old_name='time_limit',
            new_name='past_time',
        ),
    ]
