# Generated by Django 5.1.2 on 2024-10-19 19:40

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_time_limit_scavenger_hunt_past_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='scavenger_hunt',
            name='time_completed',
            field=banjo.models.IntegerField(default=0),
        ),
    ]
