# Generated by Django 5.1.2 on 2024-10-19 20:33

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_scavenger_hunt_time_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='scavenger_hunt',
            name='completed_day',
            field=banjo.models.IntegerField(default=0),
        ),
    ]
