# Generated by Django 5.1.2 on 2024-10-20 08:13

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='posted_hunts',
            field=banjo.models.StringField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='user_completed',
            field=banjo.models.IntegerField(default=0),
        ),
    ]
