# Generated by Django 5.1.2 on 2024-10-20 08:15

import banjo.models
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_user_name_user_username_user_posted_hunts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_completed',
        ),
        migrations.AddField(
            model_name='scavenger_hunt',
            name='user_posted',
            field=banjo.models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
