# Generated by Django 5.1.2 on 2024-10-20 08:32

import banjo.models
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_user_user_completed_alter_user_posted_hunts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scavenger_hunt',
            name='user_posted',
            field=banjo.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
