# Generated by Django 5.1.2 on 2024-10-20 13:17

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_scavenger_hunt_user_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=banjo.models.StringField(default='', unique=True),
        ),
    ]
