# Generated by Django 5.1.2 on 2024-10-20 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scavenger_hunt',
            old_name='user_posted',
            new_name='my_user',
        ),
    ]
