# Generated by Django 5.1.2 on 2024-10-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_user_posted_scavenger_hunt_my_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='posted_hunts',
            new_name='posted_scavenger_hunts',
        ),
    ]
