# Generated by Django 5.1.2 on 2024-10-20 15:51

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_posted_hunts_user_posted_scavenger_hunts'),
    ]

    operations = [
        migrations.AddField(
            model_name='scavenger_hunt',
            name='completed_user',
            field=banjo.models.StringField(default=''),
        ),
    ]
