# Generated by Django 5.1.2 on 2024-10-21 11:42

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_scavenger_hunt_completed_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scavenger_hunt',
            name='posted_user',
            field=banjo.models.StringField(default=''),
        ),
    ]
