# Generated by Django 5.1.2 on 2024-10-21 12:21

import banjo.models
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_user_posted_user_scavenger_hunt_posted_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scavenger_hunt',
            name='posted_user',
            field=banjo.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_hunts', to='app.user'),
        ),
    ]
